using System;
using System.ComponentModel;
using System.Windows.Forms;

namespace Lab3
{
    internal class Form1 : Form  // Changed from Form1BaseBase to Form
    {
        private IContainer components;  // This should be auto-generated by Windows Forms designer

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);  // Removed the incorrect return value capture
        }

        // Constructor
        public Form1()
        {
            InitializeComponent();  // This should be auto-generated
        }

        // Rest of your form implementation...
    }
}